/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Customer;
import Model.DataHandler;
import Model.Person;
import Model.Project;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Nuzla
 */
public class CustomerReport extends javax.swing.JInternalFrame {

    private List<Customer> customers = new ArrayList<Customer>();

    /**
     * Creates new form CustomerReport
     */
    public CustomerReport() {
        initComponents();

        
        for(Person p: DataHandler.getInstance().getAllPeople()){
        if(p instanceof Customer)
            customers.add((Customer)p);
        }
        JTable table = new JTable();
        JScrollPane scrollPane = new JScrollPane(table);

        table.setFillsViewportHeight(true);

        table.setModel(new AbstractTableModel() {
            public String getColumnName(int col) {
                switch (col) {
                    case 0:
                        return "Name";
                    case 1:
                        return "Project Name";
                    case 2:
                        return "Project Type";
                    default:
                        throw new RuntimeException("Error!");
                }
            }

            public int getRowCount() {
                return customers.size();
            }

            public int getColumnCount() {
                return 3;
            }

            public Object getValueAt(int row, int col) {
                Customer c = customers.get(row);
                Project p = DataHandler.getInstance().getProjectById(c.getProjectId());
                switch (col) {
                    case 0:
                        return c.getName().toString();
                    case 1:
                        return p.getProjectName();
                    case 2:
                        return p.getPlatform();
                    default:
                        throw new RuntimeException("Error!");
                }
            }

            public boolean isCellEditable(int row, int col) {
                return false;
            }
        });

this.add(scrollPane,BorderLayout.CENTER);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
